##############################
# Country definition for U99 #
##############################

country = {
  tag                = U99
  intrinsic_gov_type = leninist
  capital            = 4136 # 毛里求斯影子
  manpower           = 0
  # Resource Reserves
  energy         = 0
  metal          = 0
  rare_materials = 0
  oil            = 0
  supplies       = 0
  money          = 0

  nationalprovinces      = { 4136 }
  ownedprovinces         = { 4136 }
  controlledprovinces    = { 4136 }
  landdivision = { dormant = yes id = { type = 22470 id = 117002 } name = "镇嵩军第一师 "  type = infantry model = 6 locked = yes } 
  landdivision = { dormant = yes id = { type = 22470 id = 117003 } name = "镇嵩军第二师 "  type = infantry model = 6 locked = yes } 
  landdivision = { dormant = yes id = { type = 22470 id = 117004 } name = "镇嵩军第三师 "  type = infantry model = 6 locked = yes } 
  landdivision = { dormant = yes id = { type = 22470 id = 117005 } name = "镇嵩军第四师 "  type = infantry model = 6 locked = yes } 
  landdivision = { dormant = yes id = { type = 22470 id = 117006 } name = "镇嵩军第五师 "  type = infantry model = 6 locked = yes } 
  landdivision = { dormant = yes id = { type = 22470 id = 117007 } name = "镇嵩军第六师 "  type = infantry model = 6 locked = yes } 
}
